const sampleDecision = {
  id: "sample-ai-refund",
  title: "双十一 AI 自动退款上线方案",
  sourceText: "双十一前我们希望上线 AI 自动退款。业务希望尽可能全自动，研发表示完整版本至少需要四周，现在只有两周，风控要求 500 元以上退款必须人工审核。",
  scenario: "work_product",
  ownerName: "产品负责人",
  status: "active",
  currentStage: "collect",
  deadline: "双十一前两周",
  isSample: true,
  participants: [
    { id: "sample-product", name: "产品负责人", role: "决策负责人", submissionStatus: "pending" },
    { id: "sample-business", name: "业务负责人", role: "业务意见方", submissionStatus: "confirmed" },
    { id: "sample-engineering", name: "研发负责人", role: "技术意见方", submissionStatus: "confirmed" },
    { id: "sample-risk", name: "风控负责人", role: "风险意见方", submissionStatus: "confirmed" },
  ],
  artifacts: [
    {
      id: "sample-analysis",
      type: "analysis",
      status: "confirmed",
      payload: {
        title: "双十一 AI 自动退款上线方案",
        goal: "在双十一前确定第一版自动退款做哪些情况，同时避免误退款。",
        decisionQuestion: "第一版自动退款应该覆盖哪些场景？",
        participants: ["产品负责人", "业务负责人", "研发负责人", "风控负责人"],
        constraints: [
          { statement: "两周内要上线第一版", type: "soft", evidenceNeeded: false },
          { statement: "500 元以上退款必须人工审核", type: "hard", evidenceNeeded: false },
          { statement: "如果全部做完，至少需要四周", type: "assumption", evidenceNeeded: true },
        ],
        informationGaps: ["500 元以下退款占多少", "识别低风险退款的功能到底要多久"],
      },
    },
    {
      id: "sample-viewpoint-draft-product",
      type: "viewpoint_draft:sample-product",
      status: "draft",
      payload: {
        participantId: "sample-product",
        originalText: "我希望双十一前先上线一版，真正减少客服的工作量，但不能为了赶时间增加误退款风险。",
        goal: "双十一前交付一版真正能减少客服工作的自动退款能力。",
        position: "支持按期上线，但第一版范围应根据风险和工期收敛。",
        underlyingNeed: "既要证明自动退款有实际价值，也不能用不可控的误退款换速度。",
        nonNegotiables: ["不能为了赶时间明显增加误退款风险。"],
        negotiables: ["第一版不必覆盖所有退款，可以后续逐步扩大。"],
        evidence: ["双十一是客服退款处理压力较大的时间点。"],
        assumptions: ["先上线较小范围也能明显减少客服工作。"],
        openQuestions: ["多大覆盖范围才能真正减少客服工作？"],
      },
    },
    {
      id: "sample-viewpoint-business",
      type: "viewpoint:sample-business",
      status: "confirmed",
      payload: {
        participantId: "sample-business",
        originalText: "希望第一版尽量多处理一些退款，优先处理数量最多、规则最清楚的情况。",
        goal: "在业务高峰期减少尽可能多的人工退款处理。",
        position: "优先覆盖数量多、规则清楚的退款场景。",
        underlyingNeed: "希望第一版上线后能产生可感知的业务效果，而不只是完成技术展示。",
        nonNegotiables: [],
        negotiables: ["可以暂时保留复杂或高风险退款的人工处理。"],
        evidence: [],
        assumptions: ["规则清楚的退款占比较高。"],
        openQuestions: ["500 元以下退款占全部人工退款的多少？"],
      },
    },
    {
      id: "sample-viewpoint-engineering",
      type: "viewpoint:sample-engineering",
      status: "confirmed",
      payload: {
        participantId: "sample-engineering",
        originalText: "如果全部做完，至少需要四周。现在只有两周，第一版必须缩小范围。",
        goal: "在可交付、可测试的范围内按时完成第一版。",
        position: "完整版本无法在两周内交付，需要缩小第一版范围。",
        underlyingNeed: "避免为赶时间跳过必要的开发、联调和测试。",
        nonNegotiables: ["两周内不能承诺完整版本。"],
        negotiables: ["可以先完成规则更清楚、技术依赖更少的部分。"],
        evidence: ["完整范围的初步估时为四周。"],
        assumptions: ["缩小后的低风险识别能力可能在两周内完成。"],
        openQuestions: ["缩小后的风险识别功能具体需要多久？"],
      },
    },
    {
      id: "sample-viewpoint-risk",
      type: "viewpoint:sample-risk",
      status: "confirmed",
      payload: {
        participantId: "sample-risk",
        originalText: "500 元以上的退款必须由人工审核；其他退款如果出现异常，也要能马上转给人工处理。",
        goal: "在提高处理效率的同时避免高风险退款被错误执行。",
        position: "高金额退款保留人工审核，其他自动处理也必须能随时转人工。",
        underlyingNeed: "资金操作必须有清晰边界和可停止、可追查的处理路径。",
        nonNegotiables: ["500 元以上退款必须人工审核。", "出现异常时必须能停止自动处理并转人工。"],
        negotiables: ["符合已确认规则的低金额退款可以逐步自动化。"],
        evidence: ["500 元以上人工审核是已确认的风控规则。"],
        assumptions: [],
        openQuestions: ["哪些异常信号会触发转人工？"],
      },
    },
    {
      id: "sample-decision-brief",
      type: "decision_brief",
      status: "draft",
      payload: {
        commonGoal: "双十一前上线一版能减少客服工作的退款能力，同时守住误退款风险边界。",
        decisionQuestion: "两周内第一版应该自动处理哪些退款，又怎样保留人工兜底？",
        participantSummaries: [
          { participant: "产品负责人", priority: "按期交付一版有实际价值的能力", concern: "不能为了演示自动化而增加误退款" },
          { participant: "业务负责人", priority: "覆盖数量多、规则清楚的退款", concern: "范围太小可能看不到业务效果" },
          { participant: "研发负责人", priority: "范围必须能在两周内开发和测试", concern: "完整版本至少需要四周" },
          { participant: "风控负责人", priority: "高风险资金操作保留人工控制", concern: "异常订单必须能立刻转人工" },
        ],
        agreements: ["第一版应在双十一前上线。", "复杂或高风险退款可以继续人工处理。"],
        disagreements: ["第一版自动处理的范围应该有多大。", "低风险识别能力是否能在两周内完成。"],
        nonNegotiables: ["500 元以上退款必须人工审核。", "异常时必须能停止自动处理并转人工。"],
        preferences: ["尽可能提高自动处理覆盖率。", "第一版应产生可感知的客服减负效果。"],
        evidenceGaps: ["500 元以下退款的实际占比。", "缩小后的风险识别功能详细工期。"],
        boundaryNote: "产品负责人仍需要判断第一版覆盖多大范围，以及是否接受覆盖率、工期和风险之间的取舍。",
      },
    },
    {
      id: "sample-diagnosis",
      type: "diagnosis",
      status: "confirmed",
      payload: {
        demandAssessment: {
          summary: "客服现在确实很忙，但第一版不一定要处理所有退款。",
          evidenceStatus: "已有部分依据",
          recommendation: "可以继续，但先缩小第一版范围，并确认低金额退款占多少。",
        },
        conflicts: [
          {
            id: "time-scope",
            title: "功能太多，时间不够",
            sideA: "全部自动退款功能需要 4 周",
            sideB: "距离双十一只剩 2 周",
            severity: "high",
            status: "known",
            evidenceNote: "需要研发说明工期是怎样估出来的",
          },
          {
            id: "automation-risk",
            title: "多做自动退款，还是先控制风险",
            sideA: "业务希望更多退款自动处理",
            sideB: "500 元以上必须人工审核",
            severity: "critical",
            status: "known",
            evidenceNote: "已确认风控规则",
          },
        ],
        questions: [
          {
            id: "refund-share",
            owner: "业务负责人",
            question: "500 元以下的退款，大约占全部人工退款的多少？",
            why: "如果这部分很多，第一版只做低风险退款也能减少不少人工工作。",
          },
          {
            id: "classifier-timing",
            owner: "研发负责人",
            question: "缩小后的低风险识别功能，当前依据什么判断能在两周内完成？",
            why: "方案能否按期上线取决于这个模块的真实工期。",
          },
        ],
      },
    },
    {
      id: "sample-proposals",
      type: "proposals",
      status: "confirmed",
      payload: {
        proposals: [
          {
            id: "A",
            title: "推迟上线，把功能做完整",
            summary: "多做两周，等自动退款功能更完整后再上线。",
            tradeoff: "赶不上双十一前上线",
            risk: "可能错过业务最忙的时候",
            approach: "用更长工期换取更完整的首发范围。",
            whyWorthConsidering: "它展示了完整能力的上限，也能帮助负责人看清‘完整’需要付出的时间代价。",
            steps: ["重新确认四周范围和测试计划。", "调整双十一前的业务承诺。", "完整开发并通过上线检查后发布。"],
            satisfies: ["覆盖更完整的退款场景。", "给开发和测试留下较充分时间。"],
            sacrifices: ["放弃双十一前上线第一版。"],
            evidenceNeeded: ["完整范围四周估时的任务拆分。"],
            rollbackPlan: "如果延期无法被业务接受，退回按期但缩小范围的方向。",
            successSignal: "完整范围通过测试并按调整后的日期上线。",
            coverage: "high",
            timeConfidence: "low",
            riskControl: "medium",
            assumptions: [],
            meetsConstraints: false,
          },
          {
            id: "B",
            title: "只处理规则明确的低风险退款",
            summary: "按时上线，只自动处理规则明确的低风险退款，其他退款继续人工处理。",
            tradeoff: "第一版能自动处理的退款较少",
            risk: "实际减少的人工工作可能不多",
            approach: "用风险分类把低风险退款直接送入自动处理，其余情况转人工。",
            whyWorthConsidering: "它不是平均缩小所有功能，而是按风险拆分处理路径，用较小范围争取较高自动化收益。",
            steps: ["确认低风险分类标准和覆盖范围。", "完成风险分类与自动退款链路。", "异常或高金额退款转入人工队列。", "上线后抽样检查识别结果。"],
            satisfies: ["双十一前上线。", "500 元以上继续人工审核。", "低风险退款能够自动处理。"],
            sacrifices: ["复杂退款仍需要人工处理。"],
            evidenceNeeded: ["风险分类功能可在两周内完成的研发拆分。", "低风险退款占比。"],
            rollbackPlan: "分类结果异常时关闭自动执行，所有退款恢复人工处理。",
            successSignal: "在不突破风控规则的前提下，低风险退款人工处理量下降。",
            coverage: "low",
            timeConfidence: "high",
            riskControl: "high",
            assumptions: ["现有规则能在两周内识别低风险退款"],
            meetsConstraints: true,
          },
          {
            id: "C",
            title: "规则白名单自动执行，其他进入人工确认队列",
            summary: "不等待完整风险分类模块，先让风控确认一小组规则明确的白名单；命中白名单且不超过 500 元的退款自动执行，其余进入人工确认队列。",
            tradeoff: "第一版覆盖有限，还需要人工维护白名单和处理队列",
            risk: "白名单过窄会限制减负效果，过宽则可能增加误退款",
            approach: "把复杂的智能分类拆成‘确定性白名单 + 人工确认队列 + 随时关闭’三层处理。",
            whyWorthConsidering: "它绕开了完整风险分类模块的工期依赖，同时保留少量自动化和清晰的人工兜底。",
            steps: ["由风控确认首批白名单规则。", "开发白名单自动执行和人工确认队列。", "增加异常停止开关与操作记录。", "每天抽样检查并决定是否扩大白名单。"],
            satisfies: ["双十一前上线第一版。", "500 元以上保持人工审核。", "部分规则明确的退款可以自动处理。"],
            sacrifices: ["短期覆盖率低于依赖风险分类的方案。", "需要人工维护规则并处理非白名单退款。"],
            evidenceNeeded: ["首批白名单规则的风控确认。", "白名单覆盖量是否足以减轻客服压力。"],
            rollbackPlan: "发现异常时关闭白名单自动执行，所有订单进入人工确认队列。",
            successSignal: "白名单订单稳定处理，且人工队列没有因异常显著增加。",
            coverage: "medium",
            timeConfidence: "high",
            riskControl: "high",
            assumptions: ["能找到一组无需复杂分类、规则明确的低风险场景。"],
            meetsConstraints: true,
          },
        ],
      },
    },
    {
      id: "sample-validation",
      type: "validation",
      status: "confirmed",
      payload: {
        summary: "方案 B 和 C 可以继续；方案 A 需要负责人明确接受延期。",
        results: [
          { proposalId: "A", status: "human_tradeoff", reason: "赶不上双十一前上线。" },
          { proposalId: "B", status: "pass", reason: "初版任务拆分共 10 个工作日，目前看来能按时上线，也没有违反 500 元以上必须人工审核的要求。" },
          { proposalId: "C", status: "pass", reason: "不依赖完整风险分类模块，并保留高金额人工审核和异常停止路径。" },
        ],
      },
    },
    {
      id: "sample-objection-template",
      type: "objection_template",
      status: "confirmed",
      payload: {
        category: "assumption_invalidated",
        summary: "研发重新拆分任务后发现，识别低风险退款的功能至少需要三周，两周内做不完。",
        affectedProposalIds: ["B"],
        invalidatedAssumptions: ["识别低风险退款的功能可以在两周内完成"],
        recommendedAction: "方案 B 不能按时完成。如果对三周估时还有疑问，可以先确认依据；如果已经确认，就返回方案页重新选择。",
      },
    },
    {
      id: "sample-review-product",
      type: "review:sample-product",
      status: "confirmed",
      payload: {
        participantId: "sample-product",
        status: "accept",
        note: "同意先做风险较低的范围，以后再逐步扩大。",
      },
    },
    {
      id: "sample-review-business",
      type: "review:sample-business",
      status: "confirmed",
      payload: {
        participantId: "sample-business",
        status: "concern",
        note: "可以接受，但需要关注第一版到底能减少多少人工退款。",
      },
    },
    {
      id: "sample-review-risk",
      type: "review:sample-risk",
      status: "confirmed",
      payload: {
        participantId: "sample-risk",
        status: "accept",
        note: "高金额退款继续人工审核，可以接受。",
      },
    },
  ],
};

module.exports = { sampleDecision };
