const sampleDecision = {
  id: "sample-ai-refund",
  title: "双十一 AI 自动退款上线方案",
  sourceText: "双十一前我们希望上线 AI 自动退款。业务希望尽可能全自动，研发表示完整版本至少需要四周，现在只有两周，风控要求 500 元以上退款必须人工审核。",
  scenario: "work_product",
  ownerName: "产品负责人",
  status: "active",
  currentStage: "collect",
  deadline: "双十一前两周",
  isSample: true,
  participants: [
    { id: "sample-product", name: "产品负责人", role: "决策负责人", submissionStatus: "pending" },
    { id: "sample-business", name: "业务负责人", role: "业务意见方", submissionStatus: "confirmed" },
    { id: "sample-engineering", name: "研发负责人", role: "技术意见方", submissionStatus: "confirmed" },
    { id: "sample-risk", name: "风控负责人", role: "风险意见方", submissionStatus: "confirmed" },
  ],
  artifacts: [
    {
      id: "sample-analysis",
      type: "analysis",
      status: "confirmed",
      payload: {
        title: "双十一 AI 自动退款上线方案",
        goal: "在双十一前确定第一版自动退款做哪些情况，同时避免误退款。",
        decisionQuestion: "第一版自动退款应该覆盖哪些场景？",
        participants: ["产品负责人", "业务负责人", "研发负责人", "风控负责人"],
        constraints: [
          { statement: "两周内要上线第一版", type: "soft", evidenceNeeded: false },
          { statement: "500 元以上退款必须人工审核", type: "hard", evidenceNeeded: false },
          { statement: "如果全部做完，至少需要四周", type: "assumption", evidenceNeeded: true },
        ],
        informationGaps: ["500 元以下退款占多少", "识别低风险退款的功能到底要多久"],
      },
    },
    {
      id: "sample-diagnosis",
      type: "diagnosis",
      status: "confirmed",
      payload: {
        demandAssessment: {
          summary: "客服现在确实很忙，但第一版不一定要处理所有退款。",
          evidenceStatus: "已有部分依据",
          recommendation: "可以继续，但先缩小第一版范围，并确认低金额退款占多少。",
        },
        conflicts: [
          {
            id: "time-scope",
            title: "功能太多，时间不够",
            sideA: "全部自动退款功能需要 4 周",
            sideB: "距离双十一只剩 2 周",
            severity: "high",
            status: "known",
            evidenceNote: "需要研发说明工期是怎样估出来的",
          },
          {
            id: "automation-risk",
            title: "多做自动退款，还是先控制风险",
            sideA: "业务希望更多退款自动处理",
            sideB: "500 元以上必须人工审核",
            severity: "critical",
            status: "known",
            evidenceNote: "已确认风控规则",
          },
        ],
        questions: [
          {
            id: "refund-share",
            owner: "业务负责人",
            question: "500 元以下的退款，大约占全部人工退款的多少？",
            why: "如果这部分很多，第一版只做低风险退款也能减少不少人工工作。",
          },
        ],
      },
    },
    {
      id: "sample-proposals",
      type: "proposals",
      status: "confirmed",
      payload: {
        proposals: [
          {
            id: "A",
            title: "推迟上线，把功能做完整",
            summary: "多做两周，等自动退款功能更完整后再上线。",
            tradeoff: "赶不上双十一前上线",
            risk: "可能错过业务最忙的时候",
            coverage: "high",
            timeConfidence: "low",
            riskControl: "medium",
            assumptions: [],
            meetsConstraints: false,
          },
          {
            id: "B",
            title: "只处理规则明确的低风险退款",
            summary: "按时上线，只自动处理规则明确的低风险退款，其他退款继续人工处理。",
            tradeoff: "第一版能自动处理的退款较少",
            risk: "实际减少的人工工作可能不多",
            coverage: "low",
            timeConfidence: "high",
            riskControl: "high",
            assumptions: ["现有规则能在两周内识别低风险退款"],
            meetsConstraints: true,
          },
          {
            id: "C",
            title: "先处理低风险退款，再逐步扩大",
            summary: "第一版自动处理低风险退款，高风险退款继续人工确认，活动后再扩大范围。",
            tradeoff: "第一版不会完全自动化",
            risk: "需要明确什么时候转给人工处理",
            coverage: "medium",
            timeConfidence: "medium",
            riskControl: "high",
            assumptions: ["低金额退款占大多数"],
            meetsConstraints: true,
          },
        ],
      },
    },
    {
      id: "sample-validation",
      type: "validation",
      status: "confirmed",
      payload: {
        summary: "方案 B 和 C 可以继续；如果选方案 A，就要接受延期。",
        results: [
          { proposalId: "A", status: "human_tradeoff", reason: "赶不上双十一前上线。" },
          { proposalId: "B", status: "pass", reason: "目前看来能按时上线，也没有违反 500 元以上必须人工审核的要求。" },
          { proposalId: "C", status: "pass", reason: "目前没有违反已经确认、不能更改的条件。" },
        ],
      },
    },
    {
      id: "sample-objection-template",
      type: "objection_template",
      status: "confirmed",
      payload: {
        category: "assumption_invalidated",
        summary: "研发重新拆分任务后发现，识别低风险退款的功能至少需要三周，两周内做不完。",
        affectedProposalIds: ["B"],
        invalidatedAssumptions: ["识别低风险退款的功能可以在两周内完成"],
        recommendedAction: "方案 B 不能按时完成。如果对三周估时还有疑问，可以先确认依据；如果已经确认，就返回方案页重新选择。",
      },
    },
    {
      id: "sample-review-product",
      type: "review:sample-product",
      status: "confirmed",
      payload: {
        participantId: "sample-product",
        status: "accept",
        note: "同意先做风险较低的范围，以后再逐步扩大。",
      },
    },
    {
      id: "sample-review-business",
      type: "review:sample-business",
      status: "confirmed",
      payload: {
        participantId: "sample-business",
        status: "concern",
        note: "可以接受，但需要关注第一版到底能减少多少人工退款。",
      },
    },
    {
      id: "sample-review-risk",
      type: "review:sample-risk",
      status: "confirmed",
      payload: {
        participantId: "sample-risk",
        status: "accept",
        note: "高金额退款继续人工审核，可以接受。",
      },
    },
  ],
};

module.exports = { sampleDecision };
